#!/bin/bash

if [[ -f "/sys/class/thermal/thermal_zone0/temp" ]]; then
    cpu_temp=$(cat /sys/class/thermal/thermal_zone0/temp)
    echo "CPU Temperature: ${cpu_temp} m°C"
else
    echo "Error: Cannot fetch CPU temperature."
fi
